test_py36:
  image: python:3.6
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  # - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
  # - apt-get update -qy
  - apt-get update -q -y
  - pip install -r requirements.txt
  - pytest

