name: magic
channels:
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
- numpy
- astropy
- ipython
- matplotlib
- pyqt<6.0
- pysiaf
- python>=3.5
- pyyaml
- requests
- pytest
- photutils
- scipy