name: magic
channels:
- http://ssb.stsci.edu/astroconda-dev
- defaults
dependencies:
- numpy
- astropy
- ipython
- matplotlib
- pysiaf
- python>=3.5
- pyyaml
- requests
- pytest
- photutils
- scipy
- pip:
    - PyQt5