name: magic
channels:
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
- astropy
- ipython
- jupyter
- matplotlib
- notebook
- numpy
- pyqt<6.0
- pysiaf
- python>=3.5
- pyyaml
- requests
- pytest
- photutils
- scipy
- pip:
      - pytest-qt