before_script:
  - apt-get -y python3-pip
  - pip install -r requirements.txt

test:
  script:
    - echo 'something happened, maybe.'
    - pytest


# test_py36:
#   stage: test
#   script: pytest

# Resources:
# - https://henningtimm.gitlab.io/post/first_steps_with_gitlabci/
# - https://docs.gitlab.com/ee/ci/examples/test-and-deploy-python-application-to-heroku.html
# - https://medium.com/@farshid.ghods/using-gitlab-ci-feature-to-build-and-test-python-flask-application-and-mongodb-6e2de21a4219


