before_script:
  - bash
  - echo "I am heeeere"
  - echo $PATH
  - export PATH="/user/lchambers/miniconda3/bin:$PATH"
  - echo $PATH
  - conda env list
  - conda env create -f fgs-commissioning/environment.yml
  - conda env list
  - source activate jwst_magic
  - pip install fgs-commissioning/

test:
  script:
    - pytest

# Resources:
# - https://henningtimm.gitlab.io/post/first_steps_with_gitlabci/
# - https://docs.gitlab.com/ee/ci/examples/test-and-deploy-python-application-to-heroku.html
# - https://medium.com/@farshid.ghods/using-gitlab-ci-feature-to-build-and-test-python-flask-application-and-mongodb-6e2de21a4219


