before_script:
  - bash
  - export PATH="/home/lchambers/gitlab-runner-env/miniconda3/bin:$PATH"
  - echo $PATH
  - conda env list
  - source activate test_magic
  - pwd
  - ls -lrta
  - cd fgs_commissioning/
  - pwd
  - ls -lrta
  - pip install .

test:
  script:
    - pytest

# Resources:
# - https://henningtimm.gitlab.io/post/first_steps_with_gitlabci/
# - https://docs.gitlab.com/ee/ci/examples/test-and-deploy-python-application-to-heroku.html
# - https://medium.com/@farshid.ghods/using-gitlab-ci-feature-to-build-and-test-python-flask-application-and-mongodb-6e2de21a4219


