before_script:
  - bash
  - echo $USER
  - echo $PATH
  - cp -r /user/lchambers/miniconda3 ~/miniconda3
  - export PATH="~/miniconda3/bin:$PATH"
  - echo $PATH
  - conda env list
  # - create -n magic-test stsci pysiaf pip -y
  # - source activate test
  # - pip install -r fgs-commissioning/requirements.txt

test:
  script:
    - echo 'something happened, maybe.'
    - pytest

after_script:
  - conda


# test_py36:
#   stage: test
#   script: pytest

# Resources:
# - https://henningtimm.gitlab.io/post/first_steps_with_gitlabci/
# - https://docs.gitlab.com/ee/ci/examples/test-and-deploy-python-application-to-heroku.html
# - https://medium.com/@farshid.ghods/using-gitlab-ci-feature-to-build-and-test-python-flask-application-and-mongodb-6e2de21a4219


