# Config file for automatic testing at travis-ci.org

# Copied & modified from:
# - the spacetelescope/awesimsoss repo on 2/19/2019
# - the spacetelescope/mirage repo on 2/19/2019
# - https://github.com/astrofrog/example-travis-conda/blob/master/.travis.yml

language: python

python:
  - 3.6
  - 3.5

env:
  global:
      # - MAIN_CMD='python fgs-commissioning/setup.py'
      - CONDA_CHANNELS='http://ssb.stsci.edu/astroconda'
      - CONDA_ENVIRONMENT='fgs-commissioning/environment.yml'
      # - CONDA_DEPENDENCIES='pytest=3.6 sphinx'
      # - PIP_DEPENDENCIES=''
      - PYTHON_VERSION=3.6
      # - NUMPY_VERSION=stable
      # - ASTROPY_VERSION=stable
      # - EVENT_TYPE='push pull_request'
      # - MIRAGE_DATA='non_existing_path'

  # matrix:
  #     - SETUP_CMD='install'
  #     - SETUP_CMD='test'


install:
  # Install conda and other helpful things with astropy/ci-helpers
  # This also sets up and activates a test conda environment using
  # environment.yml
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
  # Install the package
  - python fgs-commissioning/setup.py
  # - conda env create -f fgs-commissioning/environment.yml
  # - conda activate magic

# command to run tests, e.g. python setup.py test
script:
  # - python -m pytest tests/
  - pytest fgs-commissioning/tests/