# Copied & modified from the spacetelescope/awesimsoss repo on 2/19/2019

# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5

install:
  - conda env create -f fgs-commissioning/environment.yml

# command to run tests, e.g. python setup.py test
script:
  - conda activate magic
  - python -m pytest tests/
  # - pytest tests --cov
  # - coveralls