channels:
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
- pip
- python>=3.8
- ipython
- jupyter
- notebook
- pyyaml
- requests
- pip:
  - git+https://github.com/spacetelescope/jwst
  - astropy>=5.0
  - matplotlib>=3.5.1
  - numpy
  - pandas
  - photutils
  - pyqt5>=5.11
  - pysiaf>=0.14.0
  - pytest
  - pytest-qt
  - scipy