channels:
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
- astropy
- ipython
- jupyter
- matplotlib>=3.3
- notebook
- numpy
- pysiaf>=0.7.1
- python>=3.7
- pyyaml
- requests
- pytest
- photutils
- scipy
- pandas
- pip
- pip:
  - pyqt5>=5.11,<6.0
  - pytest-qt
  - jwst
