channels:
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
- astropy
- ipython
- jupyter
- notebook
- numpy
- python>=3.7
- pyyaml
- requests
- pytest
- photutils
- scipy
- pandas
- pip
- pip:
  - pyqt5>=5.11,<6.0
  - pytest-qt
  - jwst
  - pysiaf>=0.12.0
  - matplotlib>=3.5.1
