channels:
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
- astropy
- ipython
- jupyter
- matplotlib>=3.3
- notebook
- numpy
- pyqt<6.0
- pysiaf>=0.7.1
- python>=3.6
- pyyaml
- requests
- pytest
- photutils
- scipy
- pandas
- pip
- pip:
  - pytest-qt
