%=============================================================================== 
% This file contains a complete set of all reference files and configuration parameters 
% needed to run a single iteration of FGS DHAS ID Simulator 
%------------------------------------------------------------------------------- 

%=============================================================================== 
% ID Reference files 
%------------------------------------------------------------------------------- 
ID_Sim_files = struct( ... 
'image_file', '', ... 
'bad_pixel_map', '', ... 
'distortion_coeffs', 'fd_genSim/FGS_Distortion_CV3.m', ... 
'telemetry_file', 'none', ... 
'star_file', '' ... 
); 

%=============================================================================== 
% ID Simulation settings 
%------------------------------------------------------------------------------- 
ID_Sim_settings = struct( ... 
'guider', 1, ... 
'iscreen', 1, ... 
'first_row', 12, ... 
'first_col', 0, ... 
'row_shift', 0, ... 
'col_shift', 0, ... 
'max_triads', 70, ... 
'max_sep_entries', 31125 ... 
); 

%=============================================================================== 
% ID IDP_Config Data Table Parameters 
%------------------------------------------------------------------------------- 
ID_data_table = struct( ... 
'Epsilon', 132000, ... 
'BadPixelPercentage', 0.25, ... 
'MatchWindow', 104, ... 
'ExcessStrayLightThre', 30000, ... 
'MergeIntensiyPercent', 0.8, ... 
'AbsMatchError', 562.5, ... 
'AttitudeError', 14.5, ... 
'IntegrationTime', 0.3406, ... 
'LowThresholdFactor', 0.2, ... 
'HighThresholdFactor', 0.4, ... 
'RelativeMatchError', 103.8, ... 
'SatPixelDiffLimit', 25000, ... 
'StripSizeX', 2048, ... 
'StripSizeY', 64, ... 
'ScanWindowSize', 8, ... 
'WhiteThreshold', 5300, ... 
'BlackThreshold', 230, ... 
'MaxNumBrightObject', 100, ... 
'SplitObjDistance', 9, ... 
'MergeDistance', 14, ... 
'RawSatPixelLimit', 55000, ... 
'PatternMatchTimeout', 200, ... 
'MaxNumStrip', 36, ... 
'NumRowOverlap', 8, ... 
'TLMRate', 16, ... 
'BadPixelExtraTimeout', 255, ... 
'BadPixelAccTimeout', 255, ... 
'FirstImgTimeout', 255, ... 
'ImageDataTimeout', 255, ... 
'ImageDataAccessTimeout', 255 ... 
); 
%=============================================================================== 
